// <auto-generated />
using Kiosco.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiosco.Migrations
{
    [DbContext(typeof(KioscoDbContext))]
    [Migration("20261009013014_CreacionInicial")]
    partial class CreacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kiosco.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Golosinas"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Snacks"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Galletitas"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Varios"
                        });
                });

            modelBuilder.Entity("Kiosco.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Nombre");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Coca-Cola 500 ml",
                            PrecioCosto = 1100m,
                            PrecioVenta = 1600m,
                            StockActual = 24,
                            StockMinimo = 12
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Agua mineral 500 ml",
                            PrecioCosto = 600m,
                            PrecioVenta = 900m,
                            StockActual = 4,
                            StockMinimo = 12
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Jugo en caja 200 ml",
                            PrecioCosto = 500m,
                            PrecioVenta = 800m,
                            StockActual = 18,
                            StockMinimo = 8
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Alfajor triple",
                            PrecioCosto = 700m,
                            PrecioVenta = 1200m,
                            StockActual = 2,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Chicles menta",
                            PrecioCosto = 350m,
                            PrecioVenta = 600m,
                            StockActual = 1,
                            StockMinimo = 6
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Caramelos masticables",
                            PrecioCosto = 200m,
                            PrecioVenta = 350m,
                            StockActual = 40,
                            StockMinimo = 15
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 3,
                            Nombre = "Papas fritas 80 g",
                            PrecioCosto = 1300m,
                            PrecioVenta = 1900m,
                            StockActual = 15,
                            StockMinimo = 6
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 3,
                            Nombre = "Maní salado 100 g",
                            PrecioCosto = 800m,
                            PrecioVenta = 1200m,
                            StockActual = 10,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 4,
                            Nombre = "Galletitas de agua",
                            PrecioCosto = 900m,
                            PrecioVenta = 1400m,
                            StockActual = 20,
                            StockMinimo = 8
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 5,
                            Nombre = "Pilas AA x2",
                            PrecioCosto = 1500m,
                            PrecioVenta = 2300m,
                            StockActual = 8,
                            StockMinimo = 3
                        });
                });

            modelBuilder.Entity("Kiosco.Models.Producto", b =>
                {
                    b.HasOne("Kiosco.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Kiosco.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
